spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 1072475547@qq.com
    password: brbgecmfciqbbffd
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000